unit GameSettings;

const
  GAME_BASE_WIDTH = 4;
  GAME_BASE_HEIGHT = 4;
  PLAYER_BALL_COUNT = 30 div 2;
  FIELD_WIDTH = 2 * GAME_BASE_WIDTH - 1;
  FIELD_HEIGHT = GAME_BASE_HEIGHT;
  FWid = FIELD_WIDTH - 1;
  FHei = FIELD_HEIGHT - 1;

end.